---
title: "PCP_betaWorkflow"
author: "Will P."
date: "5/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 00: R Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sp)
library(ggplot2)
library(ggforce) # to plot circles
library(dplyr)
library(tidyverse)
library(geosphere) # for geodist
library(useful) # for cartesian conversions
library(akima) # for irregular grid
library(reshape2) # for contor/grid


```

## 01: Input CSV into R
* Read and give headers and datatypes for each (eventually do more sophisticated validation/type detection)

```{r}
# TEST DATA: only one at a time
dataFile <- "testData/routes_bare_sm.csv" # flights to DTW
# dataFile <- "testData/routes_bare_sm.csv" # flights to DTW
# dataFile <- "testData/routes_bare_sm.csv" # flights to DTW
# dataFile <- "testData/routes_bare_sm.csv" # flights to DTW

df <- read.csv(file = dataFile)

summary(df)
class(df) # test to make sure it's a data frame

# STORE COL NAMES FOR LATER

colListOrig <- colnames(df)
latNames <- list("lat", "latitude", "y")
lonNames <- list("lon", "long", "longitude", "x")

# STARTING TO INCLUDE FORCED GENERIC COLUMN HEADINGS

df2 <- df

columnstovalidate <- ncol(df)

print(typeof(df))
#for loop
  for (col in 1:columnstovalidate){ 
      print("Hello!")
      print(col)
      print(typeof(df[[col]]))
      if(typeof(df[[col]]) == "double")
        print(max(as.numeric(df[[col]])))
      if(typeof(df[[col]]) == "integer")
        # print("It's an integer!")
        print(max(as.numeric(df[[col]])))
        #print(max(df[[col]]))
    }

    for (col in 1:ncol(df)){ 
      if(max(df[[col]],na.rm=T) <= 90.0 
         && min(df[[col]],na.rm=T) >= -90.0 
         && names(df)[[col]] %in% latNames) # lat
          df2$lat <- df$col
      if(max(df$col <= 180.0) 
         && min(df$col >= -180.0)
         && names(df)[col] %in% lonNames) # long
          df2$lon <- df$col
    }
      
      if(min(df$col == 0) # ctrBin
        && max(df$col == 1)
        && sum(df$col == 1)
          df$ctrBin <- df$col
      if(typeof(df$col) == "logical") #ctrBin
        df$ctrBin <- df$col
      if(typeof(df$col) == "character") # valName
        df$valName <- df$col
      if(typeof(df$col) == "integer" || "double") #val
        df$val <- df$col
    }

typeof(routes$isDTW)

     # obnoxiously explicit validation

if (typeof(routes$airport) != "character")
  routes$airport <- as.character(routes$airport)
if (typeof(routes$isDTW) != "logical")
  routes$isDTW <- as.logical(routes$isDTW)
if (typeof(routes$lat) != "double")
  routes$isDTW <- as.double(routes$lat)
if (typeof(routes$long) != "double")
  routes$isDTW <- as.double(routes$long)
if (typeof(routes$flightsDTW) != "integer" && typeof(routes$flightsDTW) != "double" )
  routes$flightsDTW <- as.double(routes$flightsDTW)

typeof(routes$isDTW)

```

