---
title: "Trampoliners_Data_Cleaning"
author: "Will P."
date: "6/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(zipcode)
library(tidyverse)
library(ggmap)
library(jsonlite)

dataFile <- "trampoliners_merrimackNH.csv" # trampoliner attendance
data(zipcode) # call this to make things easier below

trampoliners <- read.csv(file = dataFile)

trampolinersClean <- subset(trampoliners,trampoliners$Number.Of.Visits < 200) # remove test data
trampolinersClean <- subset(trampolinersClean,trampolinersClean$Number.Of.Visits > 0) # remove people with zero visits

plot(trampolinersClean$Age, trampolinersClean$Number.Of.Visits)

aggtrampolinersClean = aggregate(trampolinersClean$Number.Of.Visits, by=list(Category=trampolinersClean$Age), FUN=sum)

plot(aggtrampolinersClean$Category, aggtrampolinersClean$x)

```

# Zipcode join
```{r}
# clean trampolines
  # remove 5+ digit zips (CAN fine bc innerjoin)
  # remove single visit
trampolinersCleaner <- filter(trampolinersClean, trampolinersClean$Number.Of.Visits>1)

trampolineZips <- inner_join(zipcode, trampolinersCleaner, by = c("zip" = "Primary.Address.Zip"))
trampolineZips <- filter(trampolineZips, !is.na(trampolineZips$longitude))

plot(trampolineZips$longitude, trampolineZips$latitude)

trampolineZips <- aggregate(trampolineZips$Number.Of.Visits, by=list(zip=trampolineZips$zip), FUN=sum)
trampolineZips <- inner_join(zipcode, trampolineZips, by = "zip")

names(trampolineZips)[names(trampolineZips) == 'x'] <- 'visits'

trampolineZips$cityState = paste(sep="", trampolineZips$city,", ", trampolineZips$state)

## aggregate to city

trampolineCities <- aggregate(trampolineZips$visits, by=list(cityState=trampolineZips$cityState), FUN=sum)
                              

## geocode

## geocoding function using OSM Nominatim API
## details: http://wiki.openstreetmap.org/wiki/Nominatim
## made by: D.Kisler 

nominatim_osm <- function(address = NULL)
{
  if(suppressWarnings(is.null(address)))
    return(data.frame())
  tryCatch(
    d <- jsonlite::fromJSON( 
      gsub('\\@addr\\@', gsub('\\s+', '\\%20', address), 
           'http://nominatim.openstreetmap.org/search/@addr@?format=json&addressdetails=0&limit=1')
    ), error = function(c) return(data.frame())
  )
  if(length(d) == 0) return(data.frame())
  return(data.frame(lon = as.numeric(d$lon), lat = as.numeric(d$lat)))
}

 for (row in 1:nrow(trampolineCities)){
   geocode <- nominatim_osm(trampolineCities[row,"cityState"])
   trampolineCities[row, "lat"] <- geocode[2]
   trampolineCities[row, "lon"] <- geocode[1]
   print(trampolineCities[row, "cityState"])
 }

trampolineZips <- trampolineZips %>%
  add_column(isCTR = FALSE) %>%
  add_row(latitude=42.848935, longitude = -71.494521, city = "Merrimack Altitude", isCTR = TRUE)

trampolineCities <- trampolineCities %>%
  add_column(isCTR = FALSE) %>%
  add_row(lat=42.848935, lon = -71.494521, cityState = "Merrimack Altitude", isCTR = TRUE)

names(trampolineCities)[names(trampolineCities) == 'x'] <- 'visits'


#SAVE AS CSVs
write_csv(trampolineZips, "trampZips.csv")
write_csv(trampolineCities, "trampCities.csv")

```

